Volume Class Reference
Volume Class Reference
#include <Volume.hpp>
Public Member Functions
Volume ()
empty constructor
~Volume ()
destructor
void resize (const unsigned int &Nx, const unsigned int &Ny, const unsigned int &Nz)
resize (fill with zero)
unsigned int size_x () const
get size_x
unsigned int size_y () const
get size_y
unsigned int size_z () const
get size_z
double get_data (const unsigned int &kx, const unsigned int &ky, const unsigned int &kz) const
get the value at position (kx,ky,kz)
void set_data (const unsigned int &kx, const unsigned int &ky, const unsigned int &kz, const double &value)
set the value at position (kx,ky,kz)
double operator() (const double &x, const double &y, const double &z) const
get the value at any position (x,y,z) using intepolation
Volume resampled_square (const unsigned int &N) const
resample data to fit into a cube of a given size
Volume rotated_z (const double &angle) const
apply rotation to the data by a fiven angle (radian) around the z direction
Volume smoothed () const
smoothing
std::vector< float > slice_x (const unsigned &kx) const
extract a slice of data in plane x=kx. Return a texture of size Ny*Nz (access using slice_x(kx)[ky+Ny*kz])
std::vector< float > slice_y (const unsigned &ky) const
extract a slice of data in plane y=ky. Return a texture of size Nx*Nz (access using slice_x(ky)[kx+Nx*kz])
std::vector< float > slice_z (const unsigned &kz) const
extract a slice of data in plane z=kz. Return a texture of size Nx*Ny (access using slice_x(kz)[kx+Nx*ky])
std::vector< float > mip () const
Apply MIP projection along the x direction (return b&w texture of size Ny*Nz).
std::vector< std::vector< float > > ray_cast () const
Apply classical ray-casting projection along the x direction (return color texture of size 3*Ny*Nz: access using ray_cast[r=0/g=1/b=2][ky+Ny*kz]).
Static Public Member Functions
static Volume load_v4d (const std::string &filename)
load a .4d volume file
Private Member Functions
double linear_interpolation (const double &x, const double &y, const double &z) const
internal tri-linear interpolation of the value at position (x,y,z). Return 0 if out-of-bounds
Private Attributes
unsigned int Nx
size in x direction
unsigned int Ny
size in y direction
unsigned int Nz
size in x direction
std::vector< float > data
internal data as concatenated vector of float
Detailed Description
Definition at line 9 of file Volume.hpp.
Constructor & Destructor Documentation
Volume::Volume ()
empty constructor
Definition at line 7 of file Volume.cpp.
:Nx(0),Ny(0),Nz(0),data(){}
Volume::~Volume ()
destructor
Definition at line 8 of file Volume.cpp.
{}
Member Function Documentation
double Volume::get_data (const unsigned int & kx, const unsigned int & ky, const unsigned int & kz) const
get the value at position (kx,ky,kz)
Definition at line 15 of file Volume.cpp.
References data, Nx, Ny, and Nz.
Referenced by linear_interpolation(), mip(), ray_cast(), slice_x(), slice_y(), slice_z(), and smoothed().
{
    if(kx*ky*kz<Nx*Ny*Nz)
        return data[kx+Nx*(ky+Ny*kz)];
    else
        throw(std::string("Volume::get_data() outside bounds"));
}
double Volume::linear_interpolation (const double & x, const double & y, const double & z) const [private]
internal tri-linear interpolation of the value at position (x,y,z). Return 0 if out-of-bounds
Definition at line 113 of file Volume.cpp.
References get_data(), size_x(), size_y(), and size_z().
Referenced by operator()().
{
    double epsilon=1e-6;
    if(x<0 || y<0 || z<0 || x+epsilon>=size_x() || y+epsilon>=size_y() || z+epsilon>=size_z())
    {
        //outside bounds
        return 0.0;
    }
    int x0=static_cast<int>(x);
    int y0=static_cast<int>(y);
    int z0=static_cast<int>(z);
    double ux;ux=(x-x0);
    double uy;uy=(y-y0);
    double uz;uz=(z-z0);
    double f=0.0;
    //******************************************************//
    //******************************************************//
    //**********  TO DO : Tri-linear interpolation *********//
    //******************************************************//
    //******************************************************//
    f=get_data(x0,y0,z0);
    //******************************************************//
    //******************************************************//
    //**********  /TO DO :                         *********//
    //******************************************************//
    //******************************************************//
    return f;
}
Volume Volume::load_v4d (const std::string & filename) [static]
load a .4d volume file
Definition at line 31 of file Volume.cpp.
References Nx, Ny, Nz, resize(), and set_data().
Referenced by main().
{
    Volume v;
    std::ifstream stream(filename.c_str(),std::ifstream::in);
    if(!stream.good())
    {throw std::string("Error in Volume::load_v4d("+filename+") : cannot open file \n");}
    std::string buffer;
    unsigned int Nx=0,Ny=0,Nz=0;
    stream>>Nx; stream>>Ny; stream>>Nz;
    std::cout<<" find file "<<filename<<" size=("<<Nx<<","<<Ny<<","<<Nz<<")"<<std::endl;
    v.resize(Nx,Ny,Nz);
    double f;
    for(unsigned int kx=0;stream.good() && kx<Nx;++kx)
    {
        for(unsigned int ky=0;stream.good() && ky<Ny;++ky)
        {
            for(unsigned int kz=0;stream.good() && kz<Nz;++kz)
            {
                stream>>f;
                if(stream.good())
                    v.set_data(kx,ky,kz,f);
            }
        }
    }
    stream.close();
    return v;
}
std::vector< float > Volume::mip () const
Apply MIP projection along the x direction (return b&w texture of size Ny*Nz).
Definition at line 215 of file Volume.cpp.
References get_data(), size_x(), size_y(), and size_z().
Referenced by main().
{
    std::vector<float> proj(size_y()*size_z());
    for(unsigned int ky=0;ky<size_y();++ky)
    {
        for(unsigned int kz=0;kz<size_z();++kz)
        {
            //******************************************************//
            //******************************************************//
            //**********  TO DO : MIP                      *********//
            //******************************************************//
            //******************************************************//
            proj[ky+size_y()*kz]=get_data(size_x()/2.0,ky,kz);
            //******************************************************//
            //******************************************************//
            //**********  /TO DO :                         *********//
            //******************************************************//
            //******************************************************//
        }
    }
    return proj;
}
double Volume::operator() (const double & x, const double & y, const double & z) const
get the value at any position (x,y,z) using intepolation
Definition at line 108 of file Volume.cpp.
References linear_interpolation().
{
    return linear_interpolation(x,y,z);
}
std::vector< std::vector< float > > Volume::ray_cast () const
Apply classical ray-casting projection along the x direction (return color texture of size 3*Ny*Nz: access using ray_cast[r=0/g=1/b=2][ky+Ny*kz]).
Definition at line 238 of file Volume.cpp.
References get_data(), size_x(), size_y(), and size_z().
Referenced by main().
{
    std::vector<std::vector<float> >proj;
    proj.resize(3);
    proj[0].resize(size_y()*size_z());
    proj[1].resize(size_y()*size_z());
    proj[2].resize(size_y()*size_z());
    //******************************************************//
    //******************************************************//
    //**********  TO DO : Ray Casting              *********//
    //******************************************************//
    //******************************************************//
    for(unsigned int ky=0;ky<size_y();++ky)
    {
        for(unsigned int kz=0;kz<size_z();++kz)
        {
            proj[0][ky+size_y()*kz]=get_data(size_x()/2.0-2,ky,kz);
            proj[1][ky+size_y()*kz]=get_data(size_x()/2.0,ky,kz);
            proj[2][ky+size_y()*kz]=get_data(size_x()/2.0+2,ky,kz);
        }
    }
    //******************************************************//
    //******************************************************//
    //**********  /TO DO :                         *********//
    //******************************************************//
    //******************************************************//
    return proj;
}
Volume Volume::resampled_square (const unsigned int & N) const
resample data to fit into a cube of a given size
Definition at line 147 of file Volume.cpp.
References resize(), set_data(), size_x(), size_y(), and size_z().
Referenced by main().
{
    Volume vol2;vol2.resize(N,N,N);
    for(unsigned int k0=0;k0<N;++k0)
    {
        double ux=static_cast<double>(k0)/static_cast<double>(N-1);
        double x0=ux*(size_x()-1);
        for(unsigned int k1=0;k1<N;++k1)
        {
            double uy=static_cast<double>(k1)/static_cast<double>(N-1);
            double y0=uy*(size_y()-1);
            for(unsigned int k2=0;k2<N;++k2)
            {
                double uz=static_cast<double>(k2)/static_cast<double>(N-1);
                double z0=uz*(size_z()-1);
                vol2.set_data(k0,k1,k2,(*this)(x0,y0,z0));
            }
        }
    }
    return vol2;
}
void Volume::resize (const unsigned int & Nx, const unsigned int & Ny, const unsigned int & Nz)
resize (fill with zero)
Definition at line 10 of file Volume.cpp.
References data, Nx, Ny, and Nz.
Referenced by load_v4d(), resampled_square(), rotated_z(), and smoothed().
{
    data.resize(_Nx*_Ny*_Nz);
    Nx=_Nx;Ny=_Ny;Nz=_Nz;
}
Volume Volume::rotated_z (const double & angle) const
apply rotation to the data by a fiven angle (radian) around the z direction
Definition at line 174 of file Volume.cpp.
References resize(), set_data(), size_x(), size_y(), and size_z().
Referenced by main().
{
    unsigned int N=std::max(size_x(),size_y());
    Volume v2;v2.resize(N,N,size_z());
    double cos_a;cos_a=cos(angle);
    double sin_a;sin_a=sin(angle);
    for(unsigned int kx=0;kx<N;++kx)
    {
        for(unsigned int ky=0;ky<N;++ky)
        {
            for(unsigned int kz=0;kz<size_z();++kz)
            {
                //******************************************************//
                //******************************************************//
                //**********  TO DO : Rotation                 *********//
                //******************************************************//
                //******************************************************//
                double x0=kx;
                double y0=ky;
                double z0=kz;
                //******************************************************//
                //******************************************************//
                //**********  /TO DO :                         *********//
                //******************************************************//
                //******************************************************//
                double f=(*this)(x0,y0,z0);
                v2.set_data(kx,ky,kz,f);
            }
        }
    }
    return v2;
}
void Volume::set_data (const unsigned int & kx, const unsigned int & ky, const unsigned int & kz, const double & value)
set the value at position (kx,ky,kz)
Definition at line 22 of file Volume.cpp.
References data, Nx, Ny, and Nz.
Referenced by load_v4d(), resampled_square(), rotated_z(), and smoothed().
{
    if(kx*ky*kz<Nx*Ny*Nz)
        data[kx+Nx*(ky+Ny*kz)]=value;
    else
        throw(std::string("Volume::set_data() outside bounds"));
}
unsigned int Volume::size_x () const
get size_x
Definition at line 67 of file Volume.cpp.
References Nx.
Referenced by linear_interpolation(), main(), mip(), ray_cast(), resampled_square(), rotated_z(), and smoothed().
{return Nx;}
unsigned int Volume::size_y () const
get size_y
Definition at line 68 of file Volume.cpp.
References Ny.
Referenced by linear_interpolation(), main(), mip(), ray_cast(), resampled_square(), rotated_z(), and smoothed().
{return Ny;}
unsigned int Volume::size_z () const
get size_z
Definition at line 69 of file Volume.cpp.
References Nz.
Referenced by linear_interpolation(), main(), mip(), ray_cast(), resampled_square(), rotated_z(), and smoothed().
{return Nz;}
std::vector< float > Volume::slice_x (const unsigned & kx) const
extract a slice of data in plane x=kx. Return a texture of size Ny*Nz (access using slice_x(kx)[ky+Ny*kz])
Definition at line 71 of file Volume.cpp.
References get_data(), Ny, and Nz.
Referenced by main().
{
    std::vector <float> slice(Ny*Nz);
    for(unsigned int ky=0;ky<Ny;++ky)
    {
        for(unsigned int kz=0;kz<Nz;++kz)
        {
            slice[ky+Ny*kz]=get_data(kx,ky,kz);
        }
    }
    return slice;
}
std::vector< float > Volume::slice_y (const unsigned & ky) const
extract a slice of data in plane y=ky. Return a texture of size Nx*Nz (access using slice_x(ky)[kx+Nx*kz])
Definition at line 83 of file Volume.cpp.
References get_data(), Nx, and Nz.
Referenced by main().
{
    std::vector <float> slice(Nx*Nz);
    for(unsigned int kx=0;kx<Nx;++kx)
    {
        for(unsigned int kz=0;kz<Nz;++kz)
        {
            slice[kx+Nx*kz]=get_data(kx,ky,kz);
        }
    }
    return slice;
}
std::vector< float > Volume::slice_z (const unsigned & kz) const
extract a slice of data in plane z=kz. Return a texture of size Nx*Ny (access using slice_x(kz)[kx+Nx*ky])
Definition at line 95 of file Volume.cpp.
References get_data(), Nx, and Ny.
Referenced by main().
{
    std::vector <float> slice(Nx*Ny);
    for(unsigned int kx=0;kx<Nx;++kx)
    {
        for(unsigned int ky=0;ky<Ny;++ky)
        {
            slice[kx+Nx*ky]=get_data(kx,ky,kz);
        }
    }
    return slice;
}
Volume Volume::smoothed () const
smoothing
Definition at line 270 of file Volume.cpp.
References get_data(), resize(), set_data(), size_x(), size_y(), and size_z().
Referenced by main().
{
    Volume v2;v2.resize(size_x(),size_y(),size_z());
    for(unsigned int kx=1;kx<size_x()-1;++kx)
    {
        for(unsigned int ky=1;ky<size_y()-1;++ky)
        {
            for(unsigned int kz=1;kz<size_z()-1;++kz)
            {
                double f=get_data(kx  ,ky,kz);
                double fx0=get_data(kx-1,ky,kz);
                double fx2=get_data(kx+1,ky,kz);
                double fy0=get_data(kx,ky-1,kz);
                double fy2=get_data(kx,ky+1,kz);
                double fz0=get_data(kx,ky,kz-1);
                double fz2=get_data(kx,ky,kz+1);
                double v=1/12.0*(6*f+fx0+fx2+fy0+fy2+fz0+fz2);
                v2.set_data(kx,ky,kz,v);
            }
        }
    }
    return v2;
}
Member Data Documentation
std::vector<float> Volume::data [private]
internal data as concatenated vector of float
Definition at line 122 of file Volume.hpp.
Referenced by get_data(), resize(), and set_data().
unsigned int Volume::Nx [private]
size in x direction
Definition at line 116 of file Volume.hpp.
Referenced by get_data(), load_v4d(), resize(), set_data(), size_x(), slice_y(), and slice_z().
unsigned int Volume::Ny [private]
size in y direction
Definition at line 118 of file Volume.hpp.
Referenced by get_data(), load_v4d(), resize(), set_data(), size_y(), slice_x(), and slice_z().
unsigned int Volume::Nz [private]
size in x direction
Definition at line 120 of file Volume.hpp.
Referenced by get_data(), load_v4d(), resize(), set_data(), size_z(), slice_x(), and slice_y().
The documentation for this class was generated from the following files:
header/Volume.hpp
src/Volume.cpp